# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
    'name': 'Shop Properties',
    'version': '0.1',
    'category': 'Generic Modules/Product',
    'description': """ Assign Properties to Shop in Sale/Configuration/Sales/Shop Properties, then when Shop is selected in Sale Order, the properties assigned to this Shop will be writed to each order line if the product supply method is set "Produce", so if the product must be manufactured, OpenERP will automatically choose the bill of materials that matches the defined properties in the order most closely.

""",
    'author': 'BIAS',
    'depends': ['sale'],
    'update_xml': [
        'security/ir.model.access.csv',
        'sale_view.xml',
    ],
    'installable': True,
    'active': False,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
