# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
    'name': 'Bias Partner Address Price List',
    'version': '0.1',
    'category': 'Generic Modules/Product',
    'description': """ Add Pricelist to Partner Address 

Original Price List Process:
- On create new Sale Order, default Shop and his defined Pricelist will be set in the order.
- Change Sale Order Shop, will change Sale Order Pricelist to value set in selected Shop.
- Change Partner, will search for Pricelist defined in Customer/Sale & Purchase/Sale Properties/Sale Pricelist, if set, this value will be set in Sale Order, if not, not change the Sale Order Pricelist value will be done.

This module let define Pricelist in Partner Contact, so the first criteria to select pricelist is the one set in Partner Delivery Address, if is not defined, Partner default Pricelist will be set, if neither is defined, the order retains its original value.

This module supercede sale_order.onchange_partner_id adding the serch of address default pricelist, and inherit view_order_form.partner_shipping_id adding sale_order.onchange_partner_shipping_id method.

""",
    'author': 'BIAS',
    'depends': ['base','sale'],
    'update_xml': [
        'partner_view.xml',
        'sale_view.xml',
    ],
    'installable': True,
    'active': False,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
