# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "Concrete",
        "version" : "0.1",
        "author" : "Tiny",
        "website" : "http://openerp.com",
        "category" : "Unknown",
        "description": """  ConcreteERP v0.1
        This module makes the vertical of OpenERP for Concrete ERP
        Fills up all dependencies for configuring the OpenERP into a specialized ERP for the Concrete Industry.
        Inherits Stock Picking and adds on outgoing pickings:
            -Field vehicle id from fleet management
            -Field driver from hr""",
        "depends" : ['base',
                     'stock',
                     'fleet_manager',
                     'bias_partner_address_pricelist',
                     'bias_shop_properties',
                     'mrp_jit',
                     'hr'
                     ],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        "update_xml" : ['concrete_view.xml',
                        'security/ir.model.access.csv'],
        "installable": True
}
